### ISSUE TITLE
Docker compose cluster

### ISSUE THREAD

**Issue by ssipos90** [openstreetmap/osmdbt#31]
Hi,

Great work on this tool. We're beginning to use it in production in a few months, hopefully it will have a stable release by then.

I wanted to contribute back to this project so I'm posting the Docker files here for osmdbt.

We have the full cluster for OSM, osmcgimap, nginx proxy for the previous, osmdbt, postgres, planet-dump-ng, imposm3, renderd+mapnik, apache+mod_tile but I'm not sure if I was to break it in parts and post it here or post it as a whole to the openstreetmap wiki. They are containerized individually, as they should be (except for renderd and render_expire, since render_expire cannot work over TCP).

Our workflow is to have a bit of the whole environment (osm-website + tiles) as a private server for our clients.

This is the docker-compose thing I've patched up using docker mult-stage build. 

docker-compose.yml
```yml
services:
  osmpostgres:
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - osmpostgres:/var/lib/postgresql/data
  osmdbt:
    build: build/osmdbt
    environment:
      - PGDATABASE
      - PGHOST
      - PGPASSWORD
      - PGPORT
      - PGUSER
    volumes:
    - osmdbt:/data:rw
  osmdbt-builder:
    build: build/osmdbt-builder
  osmchanges:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - osmdbt:/usr/share/nginx/html:ro

volumes:
    osmdbt:
    osmpostgres:
 
```

### Building osmdbt

build/osmdbt-builder/Dockerfile
```Dockerfile
FROM debian:buster-slim

ARG OSMDBT_SRC=https://github.com/openstreetmap/osmdbt/archive/master.tar.gz

RUN set -eu; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        cmake \
        curl \
        gettext-base \
        gosu \
        libboost-filesystem-dev \
        libboost-program-options-dev \
        libbz2-dev \
        libexpat1-dev \
        libosmium2-dev \
        libpqxx-dev \
        libprotozero-dev \
        libyaml-cpp-dev \
        pandoc \
        zlib1g-dev \
        postgresql-common \
        postgresql-server-dev-all; \
    useradd -r -u 999 osmdbt; \
    mkdir /osmdbt-src /osmdbt; \
    curl -sL "$OSMDBT_SRC" | tar -xz -C /osmdbt-src --strip-components=1; \
    chown -R osmdbt /osmdbt-src /osmdbt; \
    cd /osmdbt; \
    gosu osmdbt cmake /osmdbt-src; \
    gosu osmdbt cmake --build .; \
    rm -rf /osmdbt-src; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*; 

WORKDIR /osmdbt/src
```
In binaries are avalable at `/osmdbt/src`

### Running osmdbt in Docker
This [yacron](https://github.com/gjcarneiro/yacron/) for a proper crontab in docker. It's based on the builder image.

build/osmdbt/Dockerfile
```Dockerfile
FROM osmdbt-builder

FROM debian:buster-slim

ARG YACRON_VERSION=0.11.2/yacron-0.11.2-x86_64-unknown-linux-gnu

RUN set -eu; \
    useradd -r -u 999 osmdbt; \
    mkdir -p /opt/osmdbt/data; \
    chown -R osmdbt:osmdbt /opt/osmdbt; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        libexpat1 \
        libboost-filesystem1.67.0 \
        libboost-program-options1.67.0 \
        libpqxx-6.2 \
        libyaml-cpp0.6 \
        postgresql-client-common \
        gettext \
        zlib1g; \
    curl -sL https://github.com/gjcarneiro/yacron/releases/download/$YACRON_VERSION -o /usr/local/bin/yacron; \
    chmod +x /usr/local/bin/yacron

COPY --from=osmdbt-builder /osmdbt/src/osmdbt-* /usr/local/bin/
COPY entrypoint /usr/local/bin/entrypoint
COPY --chown=osmdbt:osmdbt *.yaml* /opt/osmdbt/

VOLUME /data
WORKDIR /opt/osmdbt

USER osmdbt
ENTRYPOINT ["entrypoint"]
CMD ["run"]
```

build/osmdbt/entrypoint.sh
```sh
#!/bin/sh

set -eu

envsubst < osmdbt-config.yaml.tpl > osmdbt-config.yaml

case "$1" in
    enable) osmdbt-enable-replication;;
    disable) osmdbt-disable-replication;;
    test) osmdbt-testdb;;
    run) exec yacron -c yacron.yaml;;
    *) exec "$@" ;;
esac
```
build/osmdbt/osmdbt-config.yml.template
```yml
---
database:
    host: "$PGHOST"
    port: "$PGPORT"
    dbname: "$PGDATABASE"
    user: "$PGUSER"
    password: "$PGPASSWORD"
    replication_slot: "$PGSLOT"
log_dir: /data/logs
changes_dir: /data/changes
tmp_dir: /data/tmp
```

build/osmdbt/yacron.yaml
```yml
jobs:
  - name: replicate
    command: |
      mkdir -p /data/logs /data/changes /data/tmp
      osmdbt-get-log --catchup --quiet
      osmdbt-catchup --quiet
      osmdbt-create-diff --quiet --max-changes=50000
    schedule: "* * * * *"
  - name: cleanup
    command: find /data/logs/ -name '*.log.done' -mtime +7 -delete
    schedule: "0 0 * * 0"
```
### Postgres

image based on osmdbt-builder and postgis images. Both are based on debian:buster-slim

```Dockerfile
FROM osmdbt-builder

FROM postgis/postgis:11-3.1
COPY --from=osmdbt-builder --chown=root:root /osmdbt/postgresql-plugin/osm-logical.so /usr/lib/postgresql/11/lib/osm-logical.so

CMD ["postgres", "--wal_level=logical", "--max_replication_slots=5"]
```
